//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoFritter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoFritter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///You may obtain a copy of the License at.
        /// </summary>
        public static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        ///See the License for the specific language governing permissions and
        ///limitations under the License.
        ///
        ///This software uses the FFmpeg library that is licensed under the LGPLv2.1 license
        ///and FFmpeg.AutoGen that is licensed under the LGPLv3.0 license..
        /// </summary>
        public static string AboutText2 {
            get {
                return ResourceManager.GetString("AboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to provide feedback then please use:.
        /// </summary>
        public static string AboutText3 {
            get {
                return ResourceManager.GetString("AboutText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to export queue.
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio volume.
        /// </summary>
        public static string AudioVolumeToolTip {
            get {
                return ResourceManager.GetString("AudioVolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to start.
        /// </summary>
        public static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearExportQueue {
            get {
                return ResourceManager.GetString("ClearExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the queue.
        /// </summary>
        public static string ClearExportQueueToolTip {
            get {
                return ResourceManager.GetString("ClearExportQueueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct video timestamps.
        /// </summary>
        public static string CorrectTimeStampsCheckBox {
            get {
                return ResourceManager.GetString("CorrectTimeStampsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled then video fragments are saved with a timestamp that is corrected by the fragment&apos;s start time..
        /// </summary>
        public static string CorrectTimeStampsToolTip {
            get {
                return ResourceManager.GetString("CorrectTimeStampsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open a video.
        /// </summary>
        public static string DoubleClickToOpen {
            get {
                return ResourceManager.GetString("DoubleClickToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export queue path:.
        /// </summary>
        public static string ExportQueuePathLabel {
            get {
                return ResourceManager.GetString("ExportQueuePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;$(VideoPath)&apos; to set an export path relative to the original video&apos;s path. E.g.: &quot;$(VideoPath)\Export&quot;.
        /// </summary>
        public static string ExportQueuePathToolTip {
            get {
                return ResourceManager.GetString("ExportQueuePathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export queue.
        /// </summary>
        public static string ExportQueueWindowTitle {
            get {
                return ResourceManager.GetString("ExportQueueWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the current selection.
        /// </summary>
        public static string ExportSelection {
            get {
                return ResourceManager.GetString("ExportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string FileMenu_Exit {
            get {
                return ResourceManager.GetString("FileMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export selection.
        /// </summary>
        public static string FileMenu_Export {
            get {
                return ResourceManager.GetString("FileMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open file.
        /// </summary>
        public static string FileMenu_Open {
            get {
                return ResourceManager.GetString("FileMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to end.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string HelpMenu_About {
            get {
                return ResourceManager.GetString("HelpMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open next video.
        /// </summary>
        public static string NextVideo {
            get {
                return ResourceManager.GetString("NextVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the next video in the current folder.
        /// </summary>
        public static string NextVideoTooltip {
            get {
                return ResourceManager.GetString("NextVideoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play from selection start.
        /// </summary>
        public static string PlayFromSelectionStart {
            get {
                return ResourceManager.GetString("PlayFromSelectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play selection.
        /// </summary>
        public static string PlaySelection {
            get {
                return ResourceManager.GetString("PlaySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play until selection end.
        /// </summary>
        public static string PlayUntilSelectionEnd {
            get {
                return ResourceManager.GetString("PlayUntilSelectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveFromExportQueue {
            get {
                return ResourceManager.GetString("RemoveFromExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected item.
        /// </summary>
        public static string RemoveFromExportQueueToolTip {
            get {
                return ResourceManager.GetString("RemoveFromExportQueueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ffmpeg logs.
        /// </summary>
        public static string SaveFFMpegLogs {
            get {
                return ResourceManager.GetString("SaveFFMpegLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled then ffmpeg logs will be saved to the application&apos;s folder..
        /// </summary>
        public static string SaveFFMpegLogsToolTip {
            get {
                return ResourceManager.GetString("SaveFFMpegLogsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of selection.
        /// </summary>
        public static string SelectionEnd {
            get {
                return ResourceManager.GetString("SelectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the selection.
        /// </summary>
        public static string SelectionLength {
            get {
                return ResourceManager.GetString("SelectionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of selection.
        /// </summary>
        public static string SelectionStart {
            get {
                return ResourceManager.GetString("SelectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set end of selection.
        /// </summary>
        public static string SetSelectionEnd {
            get {
                return ResourceManager.GetString("SetSelectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set start of selection.
        /// </summary>
        public static string SetSelectionStart {
            get {
                return ResourceManager.GetString("SetSelectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartExportQueue {
            get {
                return ResourceManager.GetString("StartExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start processing of the queue.
        /// </summary>
        public static string StartExportQueueToolTip {
            get {
                return ResourceManager.GetString("StartExportQueueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step backward.
        /// </summary>
        public static string StepBackward {
            get {
                return ResourceManager.GetString("StepBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step forward.
        /// </summary>
        public static string StepForward {
            get {
                return ResourceManager.GetString("StepForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View export _queue.
        /// </summary>
        public static string ToolsMenu_ExportQueue {
            get {
                return ResourceManager.GetString("ToolsMenu_ExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ToolsMenu_Settings {
            get {
                return ResourceManager.GetString("ToolsMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon VideoFritterIcon {
            get {
                object obj = ResourceManager.GetObject("VideoFritterIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video length.
        /// </summary>
        public static string VideoLength {
            get {
                return ResourceManager.GetString("VideoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video postition.
        /// </summary>
        public static string VideoPosition {
            get {
                return ResourceManager.GetString("VideoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set audio volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Fritter.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
